apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hotel-hourly-update-data
  namespace: hotel
spec:
  schedule: "1 */1 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 3
      activeDeadlineSeconds: 60
      template:
        spec:
          containers:
          - name: curl
            image: appropriate/curl
            args:
            - /bin/sh
            - -c
            - |
              curl -X POST --fail --header "authorization: Bearer {{TOKEN}}" http://hotel-data/updater
          restartPolicy: Never
