 apiVersion: extensions/v1beta1
 kind: Ingress
 metadata:
  name: hotel-data
  namespace: hotel
  annotations:
    kubernetes.io/ingress.class: traefik
 spec:
   rules:
   - host: hotel.fista.dev
     http:
       paths:
       - path: /
         backend:
           serviceName: hotel-data
           servicePort: 80
