apiVersion: v1
kind: Service
metadata:
  labels:
    app: hotel-data
  name: hotel-data
  namespace: hotel
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hotel-data
